apiVersion: v1
kind: Pod
metadata:
  name: my-flask-app
  labels:
    app: my-flask-app
spec:
  containers:
  - name: my-flask-app
    image: my-flask-app:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 5000

